language: python
python:
- '3'
sudo: required
branches:
  only:
  - sources
install:
- pip install -r requirements.txt
script:
- make publish github
env:
  global:
    secure: gZFi0xUaD+VoYLK9KPynVL3V/CQ5tS4jF6DsNM6mqwIofuHtQBSejcwE7tEaFeiDNg9S9POE8FFqwoQ7tutmpSG8d2gGv3G1QAk6PXja8Cs1LKP+fXR+1Em+Njhb9PGGsEP+t5D8Co3wpLAx2YJ7zC2MXMhCCCTiwX2CYkDgk8ikd+0AaycC7beRRltF/CRo15A2kT5R3rjXeKQZbISBoMWzTYWDi6My6Bsgqd7SKzpOHdURkvaLbFiGUf5IiwyogrLRuYQvLXUFYX/41UNTF29u86SO+Z/SbUexrGfF4qv57KQ1se85XRrXrMngnbc73Smj6qfghvun5WuqpLlpvUlC7x929ByU0luIsOJG+FnsjunsnqhOeK94oalNAQ4BD8EYgjZiav1TNpYGwIeO4fqXEPmamyxohe8hXKNh96fiqzftNPjUXh7aYJZbaqGFf+PsbnuO6tTswDPggLz/TvAQGxxnizZZPm3BfoycXkABvIQ71liOc0KtfZKaLsajr2pg3AcbKN4K4MwZ1oJCg8WEGLqko5j3/5R2zPGN7iI0AeH5LDW5PdPbneIVGt0GUnhlTq8uxZ7gVM8KeF458TN8lU7hAj80Y0wbSicIfmMYGrxokQcj/CtvWokWxmIu3J/0ERdMUK7jrpGb/AoTmAbDV6/DqG600kH1snhrSF0=
